server:
  port: 9001

spring:
  application:
    name: springBootAPI
    
  #H2 Database
  console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: me
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


#Exception handler
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false